# Generated by Django 2.2.4 on 2020-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
